vichitr/HacktoberfestForBeginners

- Codeforces/1213B.cpp
- Codeforces/263A.cpp
> Added 1213B

- DS/python/queue.py
- DS/python/stack.py
add queue, stack DS in python language.
> add queue, stack DS in python language

- DS/php/queue.php
- DS/php/stack.php
add queue, stack DS in php language.
> add queue, stack DS in php language

- Algorithms/InterpolationSearch.py
Added Interpolation Search and Fixed Name File Conventions of the file names in the Algorithm folder. 
Please delete options that are not relevant.
> Add Interpolation Search and Name File Change

- Algorithms/C++/Kadane_Algo.cpp
- DS/C++/BST.h
Added Kadane's algorithm in C++
> Added Kadane's algorithm in C++

- DS/Linked_List/LinkedList.h
> Added Linked List in C++

- Algorithms/C++/QuickSort.cpp
Added quick sort algorithm in C++
> Added quick sort algorithm in C++

- Algorithms/Python/sieveOfEratosthenes.py
#3 
The algorithm is used to find all prime numbers smaller than given number n.
Following is the algorithm to find all the prime numbers less than or equal to a given integer n by Eratosthenes’ method:
Create a list of consecutive integers from 2 to n: (2, 3, 4, …, n).
Initially, let p equal 2, the first prime number.
Starting from p2, count up in increments of p and mark each of these numbers greater than or equal to p2 itself in the list. These numbers will be p(p+1), p(p+2), p(p+3), etc..
Find the first number greater than p in the list that is not marked. If there was no such number, stop. Otherwise, let p now equal this number (which is the next prime), and repeat from step 3.
> Algorithm: Seive of Eratosthenes: to find prime numbers

- Algorithms/C++/Bogo_sort.cpp
Added bogo sort in C++ program list
> Created bogo_sort.cpp

- Algorithms/Python/Quick_Sort.py
Added a documented implementation of Quick Sort Algorithm in Python3
> added quick sort algorithm

- Leetcode/303.py
- Leetcode/676.py
Added solutions for leetcode problems 303 and 676.
> Add leetcode problems

- Codechef/DSTAPLS.py
Python Implementation of Distribute Apples problem of August challenge 2019
> Codechef Distribute Apples Problem

- Algorithms/Go/bubbleSort.go
Bubble sort algorithm written in Go.
> Go bubbleSort algorithm

- Codechef/MINARRS.cpp
> Added Codechef LTIME71B MINARRS Solution

- Algorithms/JavaScript/quadraticZeros.js
I created a function that takes the coefficients of a quadratic and gives the two zeros. if quadratic doesn't have zeros it logs that the quadratic doesn't hit the x-axis.
> created Quadraticzeros.js

- Algorithms/C++/MergeSort.cpp
> Added merge sort in C++

- Codechef/XORAGN.py
Solution for the [XOR Again](https://www.codechef.com/MAY18A/problems/XORAGN) challenge on CodeChef.
> XORAGN Codechef

- Algorithms/C++/tohwor.cpp
Tower of Hanoi has been implemented in C++ without recursion. Refer #3
> Tower of Hanoi in C++ without recursion

- Algorithms/C/Insertion_sort.c
Insertion sort in C language implemented. Refer #3
> Insertion sort in C implemented

- Algorithms/Go/binarySearch.go
Algorithms in various languages #3
> binary search in go added

- Algorithms/JavaScript/binarySearch.js
Algorithms in various languages #3
> binary search in javascript added

- Algorithms/C++/Palindrome.cpp
I implemented Palindrome program in c++.
Refer issue #3
> Palindrome implement in c++

- Hackerrank/DayOfProgrammer.php
> Add The Day Of Programmer Chalengge

- Hackerearth/Python/Beginners-Task.py
1.  Added solution for the problem beginners-task
2.  Created a folder named 'Python' inside the \Hackerearth\
> added beginners-task problem solution for python

- Algorithms/C++/Leap Year.cpp
Program to check Leap Year in C++
refer issue #3
> Program to check Leap Year in C++

- Algorithms/C/quick_sort.c
Quick sort implemented in C. Refer issue #3
> Quick sort implemented

- Hackerrank/Python/Swap_Case.py
1.  Created a new folder for Python solutions in /Hackerrank/
2.  Added solution for Swap_Case
> added swap-case solution

- Algorithms/Java/Linear_search.java
Linear search implemented in java. Refer issue #3
> Linear search implemented in java

- LeetCode/Add_Two_Numbers.java
This is a solution for [#2 Add Two Numbers](https://leetcode.com/problems/add-two-numbers/) on Leetcode written in java.
> Solution for Leetcode Problem #2: Add Two Numbers in java

- Codechef/MAGICHF.cpp
Added solution for the codechef problem MAGICHF which appeared in the september2018 longchallenge
> Add solution for codechef problem  MAGICHF

- Hackerrank/Java/CurrencyFormatter.java
Hackerrank problem [link](https://www.hackerrank.com/challenges/java-currency-formatter/problem)
> solution for java currency formatter

- Algorithms/Java/QuickSort.java
Quick sort implemented in Java. Refer issue #3
> Quick sort implemented in Java

- Algorithms/Java/HeapSort.java
I have added HeapSort in Algorithm /Java section
> Adding heapSort in Algorithm

- Codechef/LGCD.cpp
> created LGCD.cpp

- Codechef/SALARY.cpp
Added solution for codechef problem SALARY.  Please Review.
> Created Salary.cpp

- HelloWorld/hello.c
i added printf("Happy Hacking!");
> first commit

- .vscode/settings.json
- Algorithms/C++/Num_to_English.cpp
- Algorithms/C++/Simple_Calculator.cpp
This program can change number into English digit.
> Number to English converter

- Algorithms/Python/Backtracking.py
Permutation with backtracking
Numbers are permuted in all ways possible and the backtracking algorithm traverse through all the possible ways and prints its traversing along in the terminal.
> I added a Backtracking algorithm in python

- HelloWorld/movies_tvshows.py
Give the movie or tvshow name. If it is available on the website it will give you different Torrent links for you to download.
Prerequisite : Bit torrent on your device.
> Python script for getting magnetic links of movies and tvshows

- LeetCode/game-of-life.cpp
Added the solution in the best time for Game of Life LeetCode Solution in C++
> Game of Life LeetCode Solution in C++

- Jim and the orders.c
> Create Jim and the orders.c

- Algorithms/C++/stack.cpp
this is the code of stack in C++
> stack in c++

- Algorithms/C++/Circularlinklist.cpp
- Algorithms/C++/Queue.cpp
Queue.cpp and circularlinklist.cpp.
> Queue and Circular Link List

- Algorithms/C++/DFS.cpp
> DFS Algorithm

- Codechef/ALPHABET.c
- Codechef/CANDY123.c
- Codechef/CHCHCL.c
- Codechef/CHEFSQ.c
- Codechef/CK87MEDI.c
- Codechef/FLOW004.c
- Codechef/FLOW011.c
- Codechef/FRUITS.c
- Codechef/GDOG.c
- Codechef/HS08TEST.c
- Codechef/INTEST.c
- Codechef/JOHNY.c
- Codechef/LOSTMAX.c
- Codechef/LUCKFOUR.c
- Codechef/MSNSADM1.c
- Codechef/PRB01.c
- Codechef/TICKETS5.c
- Codechef/TLG.c
- Codechef/TWOVSTEN.c
- Codechef/VOWELTB.c
- Hackerrank/Python/Arithmetic Operators.py
- Hackerrank/Python/Loops.py
- Hackerrank/Python/Mod Divmod.py
- Hackerrank/Python/Mutations.py
- Hackerrank/Python/Python If-Else.py
- Hackerrank/Python/Python: Division.py
- Hackerrank/Python/What's Your Name?.py
I have added 20 solutions from CodeChef's huge list of problems using C Programming Language which could help beginners in analyzing and comparing the solutions with theirs.  
I have also added 7 solutions from Python HackerRank.
> Added 20 solutions using C Language from CodeChef

- DS/C++/Dictionary/Table.h
This is written as a template function in C++
> Added Dictionary Linear Probing to Data Structures

- Algorithms/Python/bubbleSort.py
> Created bubbleSort.py

- DS/C++/threadedtree.h
Added threaded tree data structure, implemented in C++. #6
> Added C++ Threaded Tree

- Hackerrank/C++/apple_tree_problem
a solution to the apple tree problem found on hackerrank.com
> added the solution to the apple tree problem

- Hackerrank/Python/DijkstraShortestReach2.py
#26 Solution for Hackerrank Dijkstra Shortest Reach 2 Hackerrank
> Solution for Hackerrank Dijkstra Shortest Reach 2

- Algorithms/C++/BozoSort.cpp
- DS/C++/queueCpp.cpp
- HelloWorld/HelloWorld.html
> Dynamic Queue in C++ working on int values

- DS/C/heap.c
A simple heap implementation using C.
> heap implementation in C

- Hackerrank/C++/inputOutput.cpp
- Hackerrank/C++/insertNodeSpecificPosition.cpp
- Hackerrank/C++/insertNodeTailLinkedList.cpp
- Hackerrank/C++/mapsSTL.cpp
- Hackerrank/C++/printLinkedList.cpp
- Hackerrank/C++/sayHelloWorld.cpp
Insert Node at the tail of a linked list.
// Problem https://www.hackerrank.com/challenges/print-the-elements-of-a-linked-list
> Added new problem

- Codeforces/1216D.cpp
Created 1216 D (Swords) solution.
> created 1216D.cpp

- Algorithms/C#/BinaryInsertionSort.cs
- Algorithms/C#/BubbleSort.cs
- Algorithms/C#/HeapSort.cs
- Algorithms/C#/InsertionSort.cs
- Algorithms/C#/MergeSort.cs
- Algorithms/C#/QuickSort.cs
- Algorithms/C#/SelectionSort.cs
- Algorithms/C#/ShellSort.cs
- Algorithms/Elixir/selectionSort.exs
- Algorithms/JavaScript/HeapSort.js
- Algorithms/JavaScript/Insertionsort.js
- Algorithms/JavaScript/MergeSort.js
- Algorithms/JavaScript/Quicksort.js
- Algorithms/JavaScript/RadixSort.js
- Algorithms/JavaScript/bogoSort.js
- Algorithms/JavaScript/bubbleSort.js
- Algorithms/JavaScript/countingSort.js
- Algorithms/JavaScript/selectionSort.js
- Algorithms/Kotlin/BubbleSort.kt
- Algorithms/Kotlin/HeapSort.kt
- Algorithms/Kotlin/MergeSort.kt
- Algorithms/Kotlin/QuickSort.kt
- Algorithms/Kotlin/insertionSort.kt
- Algorithms/Kotlin/selectionSort.kt
have added more algorithms implementation for other languages. Includes algorithms like heap sort, bubble sort, selection sort etc.
> More algorithms on C#, Elixir, Javascript, Kotlin

- Hackerrank/C++/compareTheTriplets.cpp
https://www.hackerrank.com/challenges/compare-the-triplets/problem
Issue #26
> added solution to compare The triplets

- HelloWorld/helloworld.jl
- HelloWorld/helloworld.rs
hello world in rust and julia added
> hello world in more lang

- Hackerearth/Acronym.cpp
- Hackerearth/Arania Exumai Blast.cpp
- Hackerearth/Battle of Words.cpp
- Hackerearth/Max Profit.cpp
- Hackerearth/Old and Cold Numbers.cpp
- Hackerearth/Palindromic Grid.cpp
Solutions by: Abhishek Tiwari (@become)
> Add Hackerearth Solutions

- Codechef/MATCHES.cpp
Solution for codechef MATCHES.
Link for the problem: https://www.codechef.com/problems/MATCHES
> MATCHES.cpp

- Algorithms/C/fibonacci.c
add func call on main and compile with -fopenmp
> fibonacci.c

- Codechef/CHEFING.cpp
@vichitr Please review the PR and the solution.
Thanks
> Adding Chefing Solution

- HelloWorld/HelloWorld.pl
added a HelloWorld.pl perl file to the folder
> Added Perl prog

- LeetCode/First_and_last_sorted_array.java
Solution for Leetcode problem 34, Group Anagrams. Essentially create a map where unique letters are the keys.
> Java solution for Leetcode problem 34

- Algorithms/Python/SlidingWindowMinMax.py
Sliding window technique for finding the min and max sums of subset windows within an integer array. #3
> Implemented sliding window in Python

- Hackerrank/C++/bon-appetit.cpp
- Hackerrank/C++/kangaroo.cpp
- Hackerrank/C++/viralAdvertising.cpp
> Added more solutions

- Algorithms/Java/MergeSort.java
Added mergesort in Java language for hacktoberfest #3
> Created mergeSort in Java

- Hackerrank/Python/sherlockAndAnagrams.py
Sherlock and Anagrams: https://www.hackerrank.com/challenges/sherlock-and-anagrams/
Reference issue #26
> Add HR Sherlock and Anagrams python solution

- DS/Go/stack.go
> Simple stack algorithm using Golang

- Hackerrank/Python/hashTablesRansomNote.py
Hash Tables: Ransom Note: https://www.hackerrank.com/challenges/ctci-ransom-note/
References issue #26
> Add HR hashTablesRansomNote.py solution

- Hackerrank/Python/twoStrings.py
Two Strings: https://www.hackerrank.com/challenges/two-strings/
References issue #26
> Add twoStrings.py

- Hackerearth/exchangingmoney.cpp
This is an cpp implimentation of exchanging money problem of november easy 19.Ref #25
> Add exchangingmoney.cpp

- Hackerearth/determinenumber.cpp
This is a cpp solution of hackerearth determine number problem picked from november easy 19.ref #25
> Add determinenumber.cpp

- Hackerrank/C#/New Year Chaos
Two different solutions for New Year Chaos: https://www.hackerrank.com/challenges/new-year-chaos/problem
> Solution for New Year Chaos

- Algorithms/C/radix_sort.c
implemented with 2 list (double linked circular lists) in c language with minimal standart c lib
just have to pass as parameter of executable (if it's not number get as 0)
> ADD: radix_bin sort

- HelloWorld/RandomArrayGenerator.java
- HelloWorld/randomIntArrayGenerator.js
Includes:
- Java Random int array generator static method for rapid testing/verification purposes.
- JavaScript random integer array generator function for rapid testing/verification purposes.
> random int array generators

- HelloWorld/helloWorldSpanish.java
Saying "Hello World" in Spanish.
> hello world in spanish

- HelloWorld/vs_hello.py
> new print hello world
